const projects = [
  {
    slug: "the-bulldog-babysitter",
    title: "The Bulldog Babysitter",
    body: "The Bulldog Babysitter is a custom web application built with Next.js, designed exclusively for the Bulldog Babysitter family's existing customers. This platform simplifies how clients book appointments online and offers an intuitive admin panel for managing bookings and boarding details efficiently.",
    image: "/images/projects/the-bulldog-babysitter.png",
    gitLink: "https://github.com/sambidrana/bulldog-babysitter-client",
    demoLink: "https://www.thebulldogbabysitter.com/",
    mainTechnology: ["NEXT.JS", "Mongodb", "AWS S3"],
    technologies: [
      "Next.js",
      "React",
      "TailwindCSS",
      "MongoDB",
      "Mongoose",
      "Styled Components",
      "Next-Auth",
      "AWS SDK (S3)",
      "Stripe",
      "next-connect",
    ],
  },
  {
    slug: "nks-fresh",
    title: "NKS-Fresh",
    body: "NKS-Fresh is an avant-garde e-commerce platform dedicated to delivering the freshest and finest fruits right to your doorstep. With a user-centric design and an intuitive interface, shopping for nutritious fruits has never been easier or more delightful.",
    image: "/images/projects/nks-fresh.jpg",
    gitLink: "https://github.com/sambidrana/NKS-fresh-DRP-frontend",
    mainTechnology: ["NEXT.JS", "Tailwind", "Mongodb"],
    technologies: [
      "Next.js",
      "React",
      "TailwindCSS",
      "MongoDB",
      "Mongoose",
      "Styled Components",
      "Next-Auth",
      "AWS SDK (S3)",
      "Stripe",
      "next-connect",
    ],
  },
  {
    slug: "quiz-whizz",
    title: "Quiz-Whizz",
    body: "Quiz Whizz is a web application that allows players to test their knowledge by taking quizzes on various topics. It provides an interactive quiz experience with customizable settings and a leaderboard to track and compare scores with other players.",
    image: "/images/projects/quiz-whizz.jpg",
    gitLink: "https://github.com/sambidrana/quiz-wizard",
    demoLink: "https://main--peppy-swan-96d8e4.netlify.app/",
    mainTechnology: ["React", "MaterialUI", "Firebase"],
    technologies: [
      "React",
      "React Router Dom",
      "Firebase",
      "Bootstrap",
      "MUI (Material-UI)",
      "Emotion (React & Styled)",
      "Vite",
    ],
  },
  {
    slug: "bar-pretender",
    title: "Bar-Pretender",
    body: "BarPretender is a cocktail recipe app. It has two features. The one feature is that an user can choose a cocktail from a list to access a recipe. Another feature enables users to select some ingredients they have at hand and list out what cocktails can be made with selected ingredients.",
    image: "/images/projects/bar-pretender.jpg",
    gitLink: "https://github.com/sambidrana/client-barpretender",
    mainTechnology: ["React", " Ruby"],
    technologies: [
      "React",
      "React Router Dom",
      "Vite",
      "TailwindCSS",
      "Ruby on Rails (backend)",
      "JWT (Ruby gem for JSON Web Tokens)",
      "Rack-CORS (Ruby gem for handling CORS)",
    ],
  },
  {
    slug: "one-football",
    title: "OneFootball.com",
    body: "I spearheaded the development of an interactive web application that centered around the world of football, leveraging the capabilities of Ruby, JavaScript, and the Bootstrap framework. The primary objective was to offer users exhaustive and up-to-date information about football players and the sport. One of the standout features of this application is the detailed player profiles, which not only provide insights into their career trajectories but also highlight their current club affiliations. Additionally, the platform keeps tabs on players' representations and performances with their respective national teams. Continuous updates and a user-friendly interface ensure that fans and enthusiasts have access to the latest developments and statistics at their fingertips.",
    image: "/images/projects/one-football.jpg",
    gitLink: "https://github.com/sambidrana/footballapp",
    mainTechnology: ["Ruby on Rails", "JavaScript", "Bootstrap"],
    technologies: [
      "Ruby",
      "JavaScript",
      "Bootstrap",
      "bcrypt",
      "bootsnap",
      "jQuery",
    ],
  },
];

export default projects;
